<div class="page-header">
	<h1>Lista de Cursos</h1>
</div>
<?php View::content() ?>
<table class="table">
	<thead>
		<th>Nombre</th>
		<th>Modulo</th>
		<th>Creado</th>
		<th>Acciones</th>
	</thead>
	<?php foreach ($cursos as $key => $value): ?>
		<tr>
			<td><?php echo $value->nombre ?></td>
			<td><?php echo $value->nombre_modulo ?></td>
			<td><?php echo $value->creado ?></td>
			<td>
				<?php echo Html::link("curso/ver/{$value->id}","Ver curso","class='btn btn-default btn-xs'") ?>
				<?php echo Html::link("curso/editar/{$value->id}","Editar","class='btn btn-default btn-xs'") ?>
			</td>
		</tr>
	<?php endforeach ?>
</table>

<?php echo Html::link("curso/crear",'Crear Curso','class="btn btn-success"') ?>