<div role="tabpanel" class="tab-pane fade" id="clases">
  <div class="clase_video">

    <!-- <button id='volver_clases' class='btn btn-danger btn-xs'>Volver</button> -->
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
  <div class="col-md-12">
      <h4 class="page-head-line">Clases</h4>
  </div>

    <!-- Table -->
    <table class="table">
      <thead>
        <th>#</th>
        <th>Nombre</th>

        <th colspan="3">Accion</th>
      </thead>
      <?php $count=1 ?>
      <?php foreach ($gratuitos as $key => $value): ?>
        <?php if ($count%2 != 0): ?>
          <tr style="background-color: #F5E63B">
            <td><?php echo $count ?></td>
            <td><?php echo $value['curso']->nombre_curso ?></td>
            <th>
              <?php echo Html::link("curso/ver_curso/{$value['curso']->curso_id}","Ver","class='btn btn-default btn-xs'") ?>
            </th>
          </tr>
        <?php else: ?>
          <tr>
            <td><?php echo $count ?></td>
            <td><?php echo $value['curso']->nombre_curso ?></td>
            <th>
              <?php echo Html::link("curso/ver_curso/{$value['curso']->curso_id}","Ver","class='btn btn-default btn-xs'") ?>
            </th>
          </tr>
        <?php endif ?>
        <?php $count++ ?>
      <?php endforeach ?>
    </table>
  </div>
</div>
