<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Nuevo Mensaje</h4>
      </div>
      <div class="modal-body">
      <?php echo Form::open() ?>
      <div class="form-group">
        <label for="">Asunto</label>
        <?php echo Form::hidden('mensaje.creado_por',null, Auth::get('id')) ?>
        <?php echo Form::text("mensaje.asunto","class='form-control' placeholder='Asunto...'") ?>
      </div>
      <div class="form-group">
        <label for="">Mensaje</label>
        <?php echo Form::textarea("mensaje.mensaje","class='form-control' placeholder='Mensaje...'") ?>
      </div>
      <div class="form-group">
        <label for="">Administradores</label>
        <?php $admins = Load::model('usuario_admin')->getAdmins() ?>
        <select name="mensaje[para]" id="" class="form-control">
          <?php foreach ($admins as $key => $value): ?>
            <option value="<?php echo $value->id ?>"><?php echo $value->nombre ?></option>
          <?php endforeach ?>
        </select>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </div>
      <?php echo Form::close() ?>
    </div>
  </div>
</div>