<?php View::content() ?>
     <?php if ($mensajes and count($mensajes)): ?>

        <div class="media" style="height:500px;overflow-y:scroll">
        <?php foreach ($mensajes as $key => $value): ?>
          <?php if ($value->creado_por == Auth::get('id')): ?>
            <div class="pull-right">
          <?php else: ?>
            <div class="media-left media-middle">
          <?php endif ?>
            <a href="#">
              <?php if (Load::model("usuario_admin")->esAdmin($value->creado_por)): ?>
                <img src="<?php echo PUBLIC_PATH ?>img/icono_admin.png" class='media-object' width="60" alt="no image">

                <?php else: ?>
              		<?php $imagen = Load::model('fotos_usuario')->getLast($value->creado_por) ?>
	                <?php if (isset($imagen->url) and file_exists(PUBLIC_PATH.$imagen->url)): ?>
	                <img src="<?php echo PUBLIC_PATH.$imagen->url ?>" class='media-object' width="60" alt="no image">
	                <?php else: ?>
	                <img src="<?php echo PUBLIC_PATH ?>img/perfil.png" class='media-object' width="60" alt="no image">

	                <?php endif ?>
              <?php endif ?>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><?php echo $value->asunto ?></h4>
            <p>
              <?php $creado_nombre = Load::model("usuario")->find($value->creado_por) ?>
              <?php $para_nombre = Load::model("usuario")->find($value->para) ?>
              <span class="badge"><b>Escrito por:</b> <?php echo $creado_nombre->nombre ?></span>
              <span class="badge"><b>Para:</b> <?php echo $para_nombre->nombre ?></span>
            </p>
            <p>
              <?php echo $value->mensaje ?>
            </p>
          </div>
          <hr>
        <?php endforeach ?>
        </div>
      <?php else: ?>
        <center>
          <h2>Sin mensajes que leer</h2>
        </center>
      <?php endif ?>
      <hr>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Enviar Mensaje
      </button>
      <hr>
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Nuevo Mensaje</h4>
            </div>
            <div class="modal-body">
            <?php echo Form::open() ?>
            <div class="form-group">
              <label for="">Asunto</label>
              <?php echo Form::hidden('mensaje.creado_por',null, Auth::get('id')) ?>
              <?php echo Form::text("mensaje.asunto","class='form-control' placeholder='Asunto...'") ?>
            </div>
            <div class="form-group">
              <label for="">Mensaje</label>
              <?php echo Form::textarea("mensaje.mensaje","class='form-control' placeholder='Mensaje...'") ?>
            </div>
            <div class="form-group">
              <label for="">Administradores</label>
              <?php $admins = Load::model('usuario')->find("conditions: id != '".Auth::get('id')."'") ?>
              <select name="mensaje[para]" id="" class="form-control">
                <?php foreach ($admins as $key => $value): ?>
                  <option value="<?php echo $value->id ?>"><?php echo $value->nombre ?></option>
                <?php endforeach ?>
              </select>
            </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
            <?php echo Form::close() ?>
          </div>
        </div>
      </div>